name: CI for Halo's Automation Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: maven

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          maven-version: '3.8.4'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn clean test -DsuiteXmlFile=src/test/java/com/halonasaframework/automation/suites/regression.xml -Dbrowser=chrome -Dheadless=true
        env:
          JAVA_HOME: ${{ github.workspace }}/jdk-11
          PATH: ${{ github.workspace }}/jdk-11/bin:${{ env.PATH }}

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/
