name: CI for Halo's Automation Framework

on:
  pull_request:
    branches:
      - main

jobs:
  ejecutar-pruebas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Print Java version
        run: java -version

      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Ejecutar pruebas
        run: mvn clean test -DsuiteXmlFile=src/test/java/com/halonasaframework/automation/suites/regression.xml -Dbrowser=chrome -Dheadless=true
