name: CI for Halo's Automation Framework

on:
  pull_request:
    branches:
      - main

jobs:
  ejecutar-pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'

      - name: Print Java version
        run: java -version

      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Ejecutar pruebas
        run: mvn clean test -DsuiteXmlFile=src/test/java/com/halonasaframework/automation/suites/regression.xml -Dbrowser=chrome -Dheadless=true
