name: CI for Halo's Automation Framework

# This is just a simple CI configuration to run the tests when a pull request is created
# The idea is to run all the tests to make sure that the test are still working after introducing changes

on:
  pull_request:
    branches:
      - main

jobs:
  ejecutar-pruebas:
    runs-on: ubuntu-latest

    steps:
      # Consists of 4 steps:
      ## Setting up the Java version
      ## Printing the Java version (for control purposes, but it can be dismissed)
      ## Checking out of the repository
      ## Executing the tests using the regression.xml (TestNG) file and using the Chrome browser as default (firefox can be used as well)
      ## NOTE: Here, for simplicity purpose, we set up an ubuntu environment, to execute the tests
      ## NOTE: in the Edge browser we need to set up a Windows environment or a macOS for safari

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Print Java version
        run: java -version

      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Ejecutar pruebas
        run: mvn clean test -DsuiteXmlFile=src/test/java/com/halonasaframework/automation/suites/regression.xml -Dbrowser=chrome -Dheadless=true
